# Generated by Django 4.1 on 2024-07-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_reservation_re_people_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="cus_password_length",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
