# Generated by Django 4.1 on 2024-07-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_customer_cus_password_length_delete_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareoffice",
            name="so_url",
            field=models.CharField(
                default="https://map.naver.com/p/search/%EA%B3%B5%EC%9C%A0%EC%98%A4%ED%94%BC%EC%8A%A4?c=6.00,0,0,0,dh",
                max_length=200,
            ),
        ),
    ]
